### ISSUE TITLE
K8s Cloud connector for Rabbit hardcodes username/password

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-server-kubernetes#11]
Need to support the ability to specify other username/password combinations in addition to virtual host and managment UI settings.  All these values should be managed via Boot autoconfiguration so as to be able to provide an easy way to override with environment variables.

**Comment by sabbyanandan** [comment]
We do not use `spring-cloud-kubernetes-connector` dependency anymore.
