### ISSUE TITLE
K8s cloud connector for redis does not accept password or support redis cluster or Sentinel

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-server-kubernetes#12]
Related to the similar issue with AMQP.  It feels that maybe we need to move away from the cloud connector model so as to get all the autoconfiguration support from spring boot (See https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/RedisAutoConfiguration.java for the gap in functionality)

**Comment by markpollack** [comment]
See https://coreos.com/kubernetes/docs/latest/services.html#service-discovery for a description of service discovery in k8s.

**Comment by markpollack** [comment]
See https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md#discovering-services for info on service discovery via environment variales.

**Comment by trisberg** [comment]
No longer relevant
