### ISSUE TITLE
Add k8s-server to Spring Initializr

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#126]
As a developer, I'd like to add k8s-server app-starter to Spring Initializr.

**Comment by trisberg** [comment]
We don't have the k8s server versions in a BOM anywhere AFAIK, so not sure this is possible right now.

**Comment by trisberg** [comment]
This depends on the following issues:
https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/135
https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/136
https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/125

**Comment by trisberg** [comment]
This is no longer planned, closing for now.
