### ISSUE TITLE
Add some explanation for gcloud usage in getting started guide

### ISSUE THREAD

**Issue by benstadin** [spring-cloud/spring-cloud-dataflow-server-kubernetes#143]
Im following the getting started tutorial and I've stumbled on step 3:

gcloud compute disks create mysql-disk --size 200 --type pd-standard

This prompts an error: "The required property [project] is not currently set."

This is my first attempt at getting a distributed environment up and running, and this step is particularly confusing. 

I'm now about to create a project within my google account - but still I wonder how my Google account (and cloud project there), the to-be-created disk image and the server are related to each another. 

Will be great if there were 1-2 more sentences explaining this step. Any also, is it possible to do this step without gcloud at all?

**Comment by trisberg** [comment]
Did you try `gcloud init`? That should set up your environment. I think you could pass in a `--project` argument as well but I never have to do it since gcloud remembers the project I've been using. More info on gcloud can be found here -- https://cloud.google.com/sdk/docs/quickstarts

**Comment by trisberg** [comment]
Added some instruction pointers in point 1 here - http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.1.0.RC1/reference/htmlsingle/#_deploying_streams_on_kubernetes

Closing for now, please reopen if you have other suggestions for improving this.
