### ISSUE TITLE
Revisit KubernetesModuleInstanceStatus.getAttributes()

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow-server-kubernetes#15]
Revisit k8s API and assess what useful info can be turned into attributes

**Comment by ericbottard** [comment]
see https://github.com/spring-cloud/spring-cloud-dataflow-admin-kubernetes/blob/56790e60fe1be9451ea060d8785511a97108fc2d/spring-cloud-dataflow-admin-kubernetes/src/main/java/org/springframework/cloud/dataflow/module/deployer/kubernetes/KubernetesModuleInstanceStatus.java#L82

**Comment by sabbyanandan** [comment]
This is not applicable anymore.
