### ISSUE TITLE
contents/reference/html docs are missing callout images

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-dataflow-server-kubernetes#151]
http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.1.0.RC1/reference/html/configuration-security.html#configuration-security-enabling-https

![screen shot 2016-11-26 at 9 12 54 pm](https://cloud.githubusercontent.com/assets/1175891/20642670/7a70ce28-b41d-11e6-8b7f-b5430510988d.png)

The html rendered in `spring-cloud-dataflow-server-kubernetes-docs/target/contents/reference/html/index.html` is missing the [`callouts`](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-docs/src/main/docbook/images/callouts) directory.

**Comment by trisberg** [comment]
I'm currently reworking the configuration section to have some Kubernetes specific content. So this HTTPS section that only cover running locally will need to be rewritten. I have another PR #153 that will drop this part and we will have to re-add it later with specific coverage for running HTTPS in a Kubernetes environment.
