### ISSUE TITLE
Simple ticktock (time | log) stream is continually restarts on Kubernetes

### ISSUE THREAD

**Issue by pbarriscale** [spring-cloud/spring-cloud-dataflow-server-kubernetes#156]
I have an issue where deploying the example ticktock stream (time | log) does not work. The time and log apps deploy successfully to the kubernetes cluster, startup and then continually restart. Attaching logs for SCDF and the time and log apps.

I've followed the setup as described in the SCDF Kubernetes setup [http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/current-SNAPSHOT/reference/htmlsingle/#_getting_started](http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/current-SNAPSHOT/reference/htmlsingle/#_getting_started)

Thank you,
Paul

My system info.

CoreOS stable (1185.3.0) Docker 1.11.2 Kubernetes v1.3.7 3 Kubernetes nodes

[ticktock-time-bftsd.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/616984/ticktock-time-bftsd.txt)
[scdf-ej5sr.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/616982/scdf-ej5sr.txt)
[ticktock-log-0-cmdpo.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/616983/ticktock-log-0-cmdpo.txt)

**Comment by donovanmuller** [comment]
This flapping is sometimes caused by the `/health` check not returning as healthy. Whether this be because the app is taking too long to startup or because of another reason. From your logs your app seems to startup quickly so could be something else...

One way to try find out why the Pods keep restarting is to issue a `kubectl get events --watch` command and look out for any events that might indicate why the Pods are being restarted.

Also, have you enabled the [analytics feature](http://docs.spring.io/spring-cloud-dataflow/docs/1.1.0.RELEASE/reference/htmlsingle/#enable-disable-specific-features)? If so, have you got a Redis instance running and configured correctly, as this could affect the `/health` status.

**Comment by pbarriscale** [comment]
Thanks for the feedback. Helpful for tracking down issues. Attaching both the events and the overall coreos cloud-configs (1 for master, the other for the kubernetes nodes).

You are correct, both the Liveness and Readiness probes are failing for both the time and log apps.

Liveness probe failed: Get http://10.244.93.6:8080/health: dial tcp 10.244.93.6:8080: getsockopt: connection refused
Readiness probe failed: Get http://10.244.93.6:8080/info: dial tcp 10.244.93.6:8080: getsockopt: connection refused

Thanks,
Paul

[ticktock-time-z08i9.log.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/619133/ticktock-time-z08i9.log.txt)
[cloud-config-n1-master.yml.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/619135/cloud-config-n1-master.yml.txt)
[cloud-config-n2.yml.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/619137/cloud-config-n2.yml.txt)
[cloud-config-n3.yml.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/619134/cloud-config-n3.yml.txt)
[cloud-config-n4.yml.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/619138/cloud-config-n4.yml.txt)
[dns-addon.yml.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/619136/dns-addon.yml.txt)
[ticktock-log-0-xwd0r.log.txt](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/files/619139/ticktock-log-0-xwd0r.log.txt)

**Comment by trisberg** [comment]
Did you resolve this? Looking at the log files the apps are getting killed due to memory use. You could try increasing the default app memory by modifying the `SPRING_CLOUD_DEPLOYER_KUBERNETES_MEMORY` env var in the `scdf-controller.yml` file to:

```
        - name: SPRING_CLOUD_DEPLOYER_KUBERNETES_MEMORY
          value: 1024Mi
```

**Comment by pbarriscale** [comment]
Hi Thomas,

Yes that's resolved the issue for me. Thanks for your help.

Thanks,
Paul

**Comment by levystasman** [comment]
question, while stream deploy even on setting below properties from Dashboard not able to get external endpoint automatically.  If i set directly in kubernetes it works, but defeats the purpose. Any clue.

app.http.app.http.spring.cloud.deployer.kubernetes.createLoadBalancer=true
deployer.http.kubernetes.createLoadBalancer=true
