### ISSUE TITLE
Unable to deploy simple Task - launch freezes

### ISSUE THREAD

**Issue by geoand** [spring-cloud/spring-cloud-dataflow-server-kubernetes#159]
Hello,

After successfully deploying a few streams, to Spring Cloud DataFlow for Kubernetes (app version 1.1.0.RELEASE, Kubernetes cluster version 1.4.4, created via Kubeadm), I tried to deploy tasks.
The first thing I tried was to deploy the timestamp-task from Spring Cloud Task samples.
However I was unable to launch this simple task. 
The last entries in the log are the following:

```
2016-12-13T15:54:33.398234000Z 2016-12-13 15:54:33.393  INFO 1 --- [nio-9393-exec-9] o.s.c.d.s.k.DefaultContainerFactory      : Using Docker image: springcloudtask/timestamp-task:1.1.0.RC1
```

```
2016-12-13T15:54:33.398532000Z 2016-12-13 15:54:33.393  INFO 1 --- [nio-9393-exec-9] o.s.c.d.s.k.DefaultContainerFactory      : Using Docker entry point style: exec 
```

Is there something obvious that I am missing or is deployment of the Task applications not supported?

**Comment by trisberg** [comment]
It should just work, do you see a pod created for the task?

`kubectl get po -a`

**Comment by geoand** [comment]
Thank you for the immediate response!

I am not in front of a computer right now but I will check as soon as
possible.

Once thing that I neglected to mention is that the status of the task on
DataFlow dashboard was stuck at 'Launching', and no entries where written
in the task tables.

Regards,
George

**Comment by geoand** [comment]
Hello again,

After trying this multiple times I was able to get it to work.
It seems like the problem had nothing to do with Spring Cloud Dataflow. The cluster seemed to be unable to schedule the pod for execution for some reason. After clearing various deployments/replication controllers, the task worked as expected.

Thank you very much for your assistance and sorry for wasting your time on this!
