### ISSUE TITLE
spring.cloud.deployer.kubernetes.hostNetwork

### ISSUE THREAD

**Issue by tajdars** [spring-cloud/spring-cloud-dataflow-server-kubernetes#161]
org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer
(1.0.4.RELEASE)

This class should accept this flag : spring.cloud.deployer.kubernetes.hostNetwork
and apply to 
io.fabric8.kubernetes.api.model.PodSpec

This is useful when we want the pods to be hostNetwork enabled.

Thoughts ?

**Comment by trisberg** [comment]
@tajdars I moved this to the Kubernetes Deployer project: https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/99
