### ISSUE TITLE
Add a '[[configuration-security]] == Security' section to configuration.adoc

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-kubernetes#181]

**Comment by ericbottard** [comment]
There is already such a section in the core docs. Do we want k8s specific content here?
In all cases, if this is new content, I suggest *not* using the `configuration-security` anchor, as it could conflict with the core content, should it be included

**Comment by trisberg** [comment]
The idea was to provide a custom k8s section since we don't include the core one. And, there is a link in the architecture section that currently is a dead link for k8s.
