### ISSUE TITLE
Add a Helm chart for easier installation

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-dataflow-server-kubernetes#187]
Would it be beneficial to add a [Helm chart](https://github.com/kubernetes/helm) to easily install the common (Kafka, RabbitMQ, etc.) server configurations?

**Comment by markpollack** [comment]
YES!  I was just thinking of that today.  (I'm sort of prototyping a poor man's help ATM so have been reading up on it...)

**Comment by trisberg** [comment]
@donovanmuller I've created a chart here: https://github.com/trisberg/charts/tree/master/incubator/spring-cloud-data-flow

Would be great if you could try it and provide feedback.

**Comment by donovanmuller** [comment]
@trisberg Tried it now, works great. Thanks!

**Comment by trisberg** [comment]
Forked the `kubernetes/charts` so I had to rename my initial repo to https://github.com/trisberg/charts-dev

**Comment by trisberg** [comment]
@donovanmuller thanks for trying it out - I'll let you know when I get ready to submit this to the Helm charts project
