### ISSUE TITLE
Package needed k8s files

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-server-kubernetes#189]
Docs simple refer to files in github master which have two problems
1. Master is usually wrong place as it may have totally different content that what actual release have
2. Some companies don't have access to github so it'd be good if we package all they need as a zip

**Comment by sabbyanandan** [comment]
We have a helm chart to address the software provisioning on a Kubernetes cluster. For `master`, however, it is left to the end users to create and apply individual deployments as discussed in the getting-started guide. Providing a different type of packaging method may not be useful for Kubernetes users.
