### ISSUE TITLE
Metrics files refer to wrong version

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-server-kubernetes#190]
Even if I check tagged version at `github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/v1.2.0.RELEASE/src/etc/kubernetes/metrics-controller-rabbit.yml` it has
```
image: springcloudstream/metrics-collector-rabbit:1.0.0.M1
```

**Comment by jvalkeal** [comment]
Just is the problem we're facing with #189. I'd use a placeholder in above yml file and keep actual version in maven build files. Then replace those during a build as it's always a problem if you need to replace version in static files.

**Comment by trisberg** [comment]
Fixed via #198
