### ISSUE TITLE
scdf server should refer to versioned image

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-server-kubernetes#191]
Checking `github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/v1.2.0.RELEASE/src/etc/kubernetes/scdf-controller.yml` as it uses
```
image: springcloud/spring-cloud-dataflow-server-kubernetes
```
Not sure what it resolves as there is no version defined in that image setting but I'd assume that `1.2.0.RELEASE` should always fetch same version.

**Comment by sabbyanandan** [comment]
We will be addressing the version visibility via spring-cloud/spring-cloud-dataflow-server-kubernetes#209.
