### ISSUE TITLE
Document how to override memory allocation for each application

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#200]
As a developer, I'd like to document how to override memory allocation for each application.

**Acceptance:**
Document the memory allocation override in the context of an application within the stream. Specifically, explain how to use `spring.cloud.deployer.kubernetes.environmentVariables` and `JAVA_OPTIONS=` as the optional override.

**Comment by trisberg** [comment]
I don't know what section this should go in. It's not a "Getting Started" style topic and doesn't fit in the "Server Configuration" section since it is an app deployment issue.

**Comment by trisberg** [comment]
I think I'll add an "Application Configuration" section in the "Getting Started" chapter
