### ISSUE TITLE
Test SCDF deployment on KuBo

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-kubernetes#204]

**Comment by sabbyanandan** [comment]
The usual streams including counters and as well as tasks work just fine. Metrics component looks good. A scale-out stream deployment works as expected as well. Nothing seems different when comparing a plain GCP vs. BOSH provisioned Kubernetes cluster.

**Comment by trisberg** [comment]
Thanks for testing this @sabbyanandan 👍 

I've not found any issues as well, LGTM.
