### ISSUE TITLE
Producer exception when sending message to Kafka - ticktock on k8s + no messages on ticktock.time topic

### ISSUE THREAD

**Issue by alitovillegas** [spring-cloud/spring-cloud-dataflow-server-kubernetes#225]
Hi there,
The timer application throws a per-second error when trying to send its message to Kafka:

`
2017-08-03 10:20:58,805 ERROR kafka-producer-network-thread | producer-2 o.s.k.s.LoggingProducerListener:76 - Exception thrown when sending a message with key='null' and payload='{-1, 2, 11, 99, 111, 110, 116, 101, 110, 116, 84, 121, 112, 101, 0, 0, 0, 12, 34, 116, 101, 120, 116...' to topic metrics:
org.apache.kafka.common.errors.TimeoutException: Expiring 2 record(s) for metrics-0 due to 30009 ms has passed since batch creation plus linger time
`

It seems to me like these would be the records for the metrics topic, but at the same time there are no records in the ticktock.timer topic in kafka.
I'm guessing this partition key being null could be the problem. But I am not so sure why it should use some partitioning setup that is not the default one. 

Here's what I deployed:

`
dataflow:> app register --type sink --name log --uri docker://springcloudstream/log-sink-kafka-10:1.2.0.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:log-sink-kafka-10:jar:metadata:1.2.0.RELEASE
dataflow:> app register --type source --name time --uri docker://springcloudstream/time-source-kafka-10:1.2.0.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:time-source-kafka-10:jar:metadata:1.2.0.RELEASE
dataflow:> stream create --name ticktock --definition "time | log" --deploy
`

And here's my setup:
spring-cloud-dataflow-server-kubernetes: 1.3.0.BUILD-SNAPSHOT
Spring Cloud Data Flow Core: 1.3.0.BUILD-SNAPSHOT
Spring Cloud Dataflow UI: 1.3.0.BUILD-SNAPSHOT

I'm using Kafka 10 BTW.
Thanks for your support

**Comment by trisberg** [comment]
Do you have the Metrics Server running?

Looks like your `spring.cloud.dataflow.application-properties.stream.spring.cloud.stream.bindings.applicationMetrics.destination` is set to metrics? Don't set this property and the apps should not post to the metrics channel.

**Comment by alitovillegas** [comment]
Interesting, it seems like problem #1 is solved, thanks a lot! :) I actually removed it as you suggested, and now it seems to try to push to the right topic (ticktock.time). 

Still, I get a similar exception: 

2017-08-03 15:55:50.541 ERROR 1 --- [ad | producer-1] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key=‘null’ and payload=‘{-1, 1, 11, 99, 111, 110, 116, 101, 110, 116, 84, 121, 112, 101, 0, 0, 0, 12, 34, 116, 101, 120, 116...’ to topic ticktock.time:

org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for ticktock.time-0 due to 30228 ms has passed since batch creation plus linger time

Any ideas?

**Comment by viniciusccarvalho** [comment]
It looks odd that the metrics was enabled, it should not be in first place. Are you passing any properties to the apps? Or just vanilla `time | log` from the apps 1.2.0 release?

**Comment by trisberg** [comment]
Also, can you share your server config, try something like `kubectl get rc/scdf -o json`
