### ISSUE TITLE
[Helm Chart] Default "admin" security configs don't allow stream creation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#237]
As a user, I've provisioned SCDF via the latest helm-chart; however, with the default [`admin` user credentials](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/7cf2fb094e3121f0baf52627ad6a262a759e2872/spring-cloud-dataflow-server-kubernetes-docs/src/main/asciidoc/configuration.adoc#L76), I'm unable to create streams. 

**Acceptance:**
The `admin` is a super-user equivalent account. It might be useful to map it to `ROLE_CREATE` role by default.

**Comment by trisberg** [comment]
This is a core Data Flow problem, that's where the permission mapping is done.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow#2276
