### ISSUE TITLE
Support comma in environmentProperty value

### ISSUE THREAD

**Issue by tgrafford** [spring-cloud/spring-cloud-dataflow-server-kubernetes#238]
We are using `spring.cloud.deployer.kubernetes.environmentVariables` to set default environment variables to a pod. 
This works well, except when you need to add a list of values to a environment variable (which also splits on comma). 

For example; we are unable to add more than one broker to the `spring.cloud.stream.kafka.binder.brokers` property due to this limitation. 

A workaround for this is to add the property to each app in a stream, but it is tedious and requires more configuration than what should have been necessary.

**Comment by dturanski** [comment]
Comma delimited property values will need to be wrapped in single quotes.
