### ISSUE TITLE
The docker image of 1.2.2.RELEASE should not be 'latest'

### ISSUE THREAD

**Issue by rwenz3l** [spring-cloud/spring-cloud-dataflow-server-kubernetes#240]
Since currently 1.2.2.RELEASE seems to be the 'stable' build for k8s I'd like to point out that it is using the latest tag for the docker image:

https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/9565f8ff0eb1788cd442aedb0cea4f685a9143ad/src/kubernetes/server/server-deployment.yaml#L16

This should IMO read 1.2.2.RELEASE to ensure future compatibility.

**Comment by sabbyanandan** [comment]
Hi, @rwenz3l. Thanks for reporting! A general improvement is targeted via spring-cloud/spring-cloud-dataflow-server-kubernetes#246. We are planning to address it in 1.3 RC milestone. In the meantime, you can manually change the tag to the desired [GA-tag](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-kubernetes/tags/). 

If you have any other thoughts to share, feel free to leave a comment in #246.
