### ISSUE TITLE
Liveliness and Readiness probes continuously failing after the first check (SCDF-Kubernestes)

### ISSUE THREAD

**Issue by mayuriedhara** [spring-cloud/spring-cloud-dataflow-server-kubernetes#241]
We are working on a spring cloud stream with boot applications where the stream is deployed on to the kubernetes thru SCDF. We have configured the liveliness and readiness probes to have initial Delay - 900, timeout seconds - 120 and period seconds -360. The boot applications in the stream take about 600-800 seconds to start. we are using spring boot 1.5.1 with camden.SR6 cloud dependencies. Our streams with these probes had worked for about a 2 months before an upgrade to Dalston.SR4 was done along with updates to boot. Since the upgrade, the probes started failing, so we downgraded the versions back to what they were and still noticed that the probes succeeded the first check where as they fail on the consecutive checks. We are not able to identify what the route cause since the applications within the pods have started fine. Any kind of suggestion would be of greater help. Thanks!

**Comment by viniciusccarvalho** [comment]
We noticed that the type of machines in your cluster can have a huge impact. We tweaked the default values of the probes recently, but anything less than a high-cpu 4 core machine in GKE is prone to cause issues with startup times. We are running with high cpu machines and found no issues so far.
