### ISSUE TITLE
Set docker-image to the released version instead of "latest"

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#246]
As a developer, I'd like to set the server's docker-image to the released version as opposed to the "latest" tag.

**Notes:**
- Publish and tag SNAPSHOT images in [docker-hub](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-kubernetes/tags/). This will be a change in [K8S CI plan](https://build.spring.io/build/admin/edit/editBuildTasks.action?buildKey=SCD-K8SBMASTER-K8SDOCKER).
- Parameterize server version in [server-deployment.yaml](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/9565f8ff0eb1788cd442aedb0cea4f685a9143ad/src/kubernetes/server/server-deployment.yaml#L16) (e.g., `image: springcloud/spring-cloud-dataflow-server-kubernetes:{SERVER-VERSION}`.
- Pull the "version" from the server's [pom.xml](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/master/spring-cloud-dataflow-server-kubernetes/pom.xml#L10) and replace `{SERVER-VERSION}` token in `server-deployment.yaml` - at build time.
- Remove the following note in [reference guide](https://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.3.0.M3/reference/htmlsingle/#_deploying_using_kubectl).

> change latest to the version you would like. This document is based on the 1.3.0.M3 version so the recommended image tag to use for this is latest.

**Comment by markpollack** [comment]
Will do this manually before/after the release.
