### ISSUE TITLE
Fix docs build on CI

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#253]
We are seeing:

> asciidoctor: ERROR: partintro block can only be used when doctype is book and it's a child of a book part. Excluding block content.
> Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:1.0' as the value of the DISPLAY variable.

See example [here](https://build.spring.io/browse/SCD-K8SBMASTER-672).

**Comment by viniciusccarvalho** [comment]
Fixed via 844fa86
