### ISSUE TITLE
Document how to use private Docker Registry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#269]
As a user, I'm trying to setup SCDF to resolve images from a private Docker Registry and I do not know how. 

See [SO thread](https://stackoverflow.com/questions/49291314/how-can-spring-cloud-dataflow-app-use-private-docker-repository) for background. We have recommended two approaches, but none of it appears to have worked. 

**Acceptance:**
- Setup a private Docker Registry in K8S and configure SCDF to use that
- Document the steps and the e2e solution

**Comment by chrisjs** [comment]
doc update PR is at: https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/pull/271

PR for per app secret setting is at: https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/207
