### ISSUE TITLE
Kubernetes Server/Deployer pushes app properties command line

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-server-kubernetes#270]
Problem with this is that database passwords show up in the clear for batch jobs.  Also that means that the passwords are stored in the repository for task-executions as well as batch.

Step to reproduce:
1) Create Task Definition `foo` with timestamp-batch.
2) Launch `foo`
3) Look at task-execution for the launch. You will see the arguments with the password redacted.
4) Look at the Job Execution Details.  Password is shown in the clear.

This does not occur on local server.

**Comment by cppwfs** [comment]
Refer to issue: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2125

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-deployer-kubernetes#209
