### ISSUE TITLE
Problem passing multiple spring profiles as environment variable in k8s deployer

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-dataflow-server-kubernetes#276]
We are running SCDF on Kubernetes and use a Config Server to supply configuration to stream apps (eg the rabbit location and credentials). To do this we use the following:

`deployer.http.kubernetes.environmentVariables=SPRING_CLOUD_CONFIG_URI=<my_uri>,SPRING_PROFILES_ACTIVE=production`

in our SCDF configuration.Recently we have had to add a second profile ie

`deployer.http.kubernetes.environmentVariables=SPRING_CLOUD_CONFIG_URI=<my_uri>,SPRING_PROFILES_ACTIVE=production,us-west-2`

But we get an error on deployment 'Invalid environment variable declared: us-west-2'

It looks like an issue with the string parsing ie we can't have a comma separated environment variable value. I've tried some simple quoting around the value but can't find a way to get this to work - is there a way to do this or is this something that needs fixed?

**Comment by chrisjs** [comment]
moved to https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/219

**Comment by djgeary** [comment]
This is still an issue for us - I've added a comment to spring-cloud/spring-cloud-deployer-kubernetes#219
