### ISSUE TITLE
Document "cluster-admin" role requirement for Minikube

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#282]
As a user, I'm attempting to helm install SCDF on Minukube, but the installation fails with access permission errors as shown below.

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/pods/scdf-server-869d56967c-97lsd. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "scdf-server-869d56967c-97lsd" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default".
```

See this [StackOverflow thread](https://stackoverflow.com/questions/50002213/kubernetes-service-accounts-permissions-issue-with-spring-cloud-data-flow-serv/50002919?noredirect=1#comment87062465_50002919) for background.

**Acceptance:**
Document how to create `cluster-admin` role in minikube.

**Comment by chrisjs** [comment]
with a clean install of k8s 1.10 on minikube 0.26.1 and following the helm install directions at: https://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.4.0.RELEASE/reference/htmlsingle/#_helm_installation

i.e.:

```
$ helm init
$ helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
$ helm repo update
$ helm install --name my-release --set server.service.type=NodePort incubator/spring-cloud-data-flow
```

i was unable to reproduce any error on install and didn't need to run `kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default`. i was also able to run ticktock without issue.

**Comment by sabbyanandan** [comment]
I do not know how I ended up in this state, but I couldn't reproduce it either. I tried it with and without `kubeadm` bootstrappers, but nothing on that either.
