### ISSUE TITLE
Create 1.4.x branch and create CI plans

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-server-kubernetes#285]
Create a total of 3 new plans against the 1.4.x branch.

 A plan is needed for each k8s environment

* 1.7 - clone https://build.spring.io/browse/SCD-K8S17BMASTER and use key K8S17B14x
* 1.8 - clone https://build.spring.io/browse/SCD-K8S18BMASTER and use key K8S18B14x
* 1.9 - clone https://build.spring.io/browse/SCD-K8SBMASTER and use key K8S19B14x

Disable the 1.3.x plan.

**Comment by chrisjs** [comment]
update deployment guide URL `https://build.spring.io/browse/SCD-K8S13X` as appropriate

**Comment by chrisjs** [comment]
new plans:

https://build.spring.io/browse/SCD-K8S17B14X
https://build.spring.io/browse/SCD-K8S18B14X
https://build.spring.io/browse/SCD-K8S19B14X

**Comment by sabbyanandan** [comment]
@chrisjs: Please make sure they don't run at the same time as `master` and AT CI runs. We need to schedule them with different frequencies.

**Comment by chrisjs** [comment]
@sabbyanandan the trigger configuration is set to "Repository Polling" rather than a scheduled time
