### ISSUE TITLE
Create Acceptance Test plan for 1.4.x classic/skipper

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-server-kubernetes#287]
Depends on spring-cloud/spring-cloud-dataflow-acceptance-tests#158

Need to decide how many k8s versions to test against

**Comment by sabbyanandan** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/pull/161.

**Comment by chrisjs** [comment]
new plans:

* https://build.spring.io/browse/SCDT-KSC5
* https://build.spring.io/browse/SCDT-KSS7

both have been run and are green
