### ISSUE TITLE
Update Helm chart to 1.5 GA

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#289]

**Comment by markpollack** [comment]
Note: need to wait until the metrics server goes GA

**Comment by sabbyanandan** [comment]
Depends on #303.

**Comment by chrisjs** [comment]
PR to k8s charts: https://github.com/kubernetes/charts/pull/6378

**Comment by chrisjs** [comment]
compat chart at doc/(1.5.1|current)/reference/htmlsingle/#_helm_installation should also be updated
