### ISSUE TITLE
Publish 1.4.1.BUILD-SNAPSHOT to Docker Hub

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#290]
This would something similar to https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/commit/917dbd1ed24ce7c866b2cd007f565b4cc1c20239, but we shouldn't be tagging `latest` as well.

**Comment by chrisjs** [comment]
https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-kubernetes/tags/
