### ISSUE TITLE
Prepare helm-chart for v1.6

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#304]

**Comment by chrisjs** [comment]
compat chart at /reference/htmlsingle/#_helm_installation should also be updated

**Comment by chrisjs** [comment]
ive got changes prepared locally for this -- right now its just bumping dataflow k8s to 1.6.0.RELEASE.

do we expect any other changes needed?

**Comment by sabbyanandan** [comment]
This should just be a version bump, so what you already have could be ready to go as-is.

**Comment by chrisjs** [comment]
ok sounds good, we will have to wait until 1.6.0.RELEASE is out so the image is resolvable to their CI, otherwise we are set to go on this

**Comment by chrisjs** [comment]
pr @ https://github.com/helm/charts/pull/6871
