### ISSUE TITLE
Unclear getting-started instruction for Kafka

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#306]
As a user, while attempting to orchestrate KStreams and Kafka binder based Apps, I couldn't find any clear instructions on how to switch to Kafka. In particular, there is no mention of KStreams binder configs. 

**Acceptance:**
- Though we have the mention of `If you’d like to orchestrate stream processing pipelines with Apache Kafka as the messaging middleware using Skipper, you must change the values in the SPRING_APPLICATION_JSON environment variable:` as a NOTE, it is nor explicit enough for the users. Perhaps it'd be better to split the configs for Kafka and Rabbit each, as separate sections.
- Include a copyable JSON for Rabbit, Kafka, and Kafka + KStreams excplicitly.
- Clarify the reasoning for when Kafka and KStreams are used together.

**Comment by chrisjs** [comment]
stopping until after M1 is out
