### ISSUE TITLE
"File must exist" error on maven stream deployment

### ISSUE THREAD

**Issue by naureen-34** [spring-cloud/spring-cloud-dataflow-server-kubernetes#314]
When I try to deploy a maven based stream I get following error in the shell:
`
2018-07-20 11:30:12.625 ERROR 1 --- [p-nio-80-exec-8] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
 java.lang.IllegalArgumentException: File must exist
	at org.springframework.boot.loader.data.RandomAccessDataFile.&lt;init&gt;(RandomAccessDataFile.java:67) ~[spring-cloud-dataflow-server-kubernetes.jar:1.2.2.RELEASE]`

The docker image is there and I can see it, not able to figure out why it says file does not exist.

**Comment by chrisjs** [comment]
Only docker images can be deployed to maven. You had mentioned "a maven based stream" but then also "The docker image is there and I can see it" -- what is the location you are passing to `--uri` when registering apps?

**Comment by sabbyanandan** [comment]
Hi, @naureen-34. +1 to Chris' comment ^^. Please refer to the [getting-started/installation](http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.5.2.RELEASE/reference/htmlsingle/#_installation) section re: Docker requirement. If you follow the guide, we will point to a few samples, which you could try on your cluster, and let us know your findings.

**Comment by naureen-34** [comment]
@chrisjs  I am passing --uri docker:<name of the docker image>:<tag>
@sabbyanandan sure, I will give it a try.

**Comment by naureen-34** [comment]
@sabbyanandan  I followed the documentation, in the documentation app registration has been done for a task while I am trying to register a processor with the following command:

`dataflow:>app register --name test-transformer --type processor --uri docker:/test-transformer:latest --metadata-uri file:///root/.m2/repository/com/my-project/test-transformer-0.0.5-SNAPSHOT-metadata.jar`
on running this I do see 
`Successfully registered application 'processor:test-transformer` in the shell.

Though when I request for it's info I see the following:
```
dataflow:>app info processor:eclaim-claim-transformer
Application info is not available for processor:eclaim-claim-transformer
```
When I create a stream using this processor:
`stream create --definition "http --port=9000 | test-transformer | log" --name testTransformerStream`
On deploying the stream, I see the error I mentioned above in my dataflow server log.

What am I missing here?

**Comment by sabbyanandan** [comment]
Thanks for the follow-up. It appears you're referring to the metadata artifact via `file://` protocol. And specifically, it appears you're trying to resolve it from the local Maven repository. It won't work. The stacktrace should print which artifact is failing to resolve. 

Let me clarify why.

1) In a Kubernetes environment, the artifact resolution (in SCDF) typically is a Docker artifact. Though you're resolving the App bits from a Docker Registry, but your metadata file won't be visible to SCDF. The `file://` protocol means the artifact is expected to be available in the container where SCDF is running. Is it available?
2) Speaking of Docker Registry, your k8s environment has access to the registry? Can it access and download `test-transformer:latest`?

A quick way to rule out the environmental issues would be to try out one of the samples. Use the following stream definition to see if gets deployed.

```
dataflow:>app register --type source --name time --uri docker://springcloudstream/time-source-rabbit:1.3.1.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:time-source-rabbit:jar:metadata:1.3.1.RELEASE
dataflow:>app register --type sink --name log --uri docker://springcloudstream/log-sink-rabbit:1.3.1.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:log-sink-rabbit:jar:metadata:1.3.1.RELEASE
stream create --name ticktock --definition "time | log" --deploy
```

**Comment by chrisjs** [comment]
hi @naureen-34 -- as i don't have access to your artifacts, i created the following sample which should replicate your use case and i tested it on minikube 0.27.0 / k8s 1.10

you should be able to replicate the same concept to your local environment and be able to resolve your metadata artifacts from the mount as shown below. feel free to re-open if this does not work for you

* add mount config to src/kubernetes/server/server-deployment.yaml, the relevant parts are:

```
    spec:
      volumes:
        - name: host-mount
          hostPath:
            path: /home/.m2
      containers:
      - name: scdf-server
        workingDir: /home/.m2
        volumeMounts:
        - name: host-mount
          mountPath: /home/.m2
```

* start mount daemon when minikube starts
`minikube start --mount-string /Users/cschaefer/.m2:/home/.m2 --mount`

* deploy dataflow to k8s

* connect with shell, register apps, look at info, deploy stream

```
dataflow:> app register --type source --name time --uri docker://springcloudstream/time-source-rabbit:1.3.1.RELEASE --metadata-uri file:///home/.m2/repository/org/springframework/cloud/stream/app/time-source-rabbit/1.3.1.RELEASE/time-source-rabbit-1.3.1.RELEASE-metadata.jar
Successfully registered application 'source:time'
dataflow:> app info --name time --type source
Information about source application 'time':
Resource URI: docker://springcloudstream/time-source-rabbit:1.3.1.RELEASE
╔══════════════════════════════╤══════════════════════════════╤══════════════════════════════╤══════════════════════════════╗
║         Option Name          │         Description          │           Default            │             Type             ║
╠══════════════════════════════╪══════════════════════════════╪══════════════════════════════╪══════════════════════════════╣
║trigger.time-unit             │The TimeUnit to apply to delay│<none>                        │java.util.concurrent.TimeUnit ║
║                              │values.                       │                              │                              ║
║trigger.fixed-delay           │Fixed delay for periodic      │1                             │java.lang.Integer             ║
║                              │triggers.                     │                              │                              ║
║trigger.cron                  │Cron expression value for the │<none>                        │java.lang.String              ║
║                              │Cron Trigger.                 │                              │                              ║
║trigger.initial-delay         │Initial delay for periodic    │0                             │java.lang.Integer             ║
║                              │triggers.                     │                              │                              ║
║trigger.max-messages          │Maximum messages per poll, -1 │1                             │java.lang.Long                ║
║                              │means infinity.               │                              │                              ║
║trigger.date-format           │Format for the date value.    │<none>                        │java.lang.String              ║
╚══════════════════════════════╧══════════════════════════════╧══════════════════════════════╧══════════════════════════════╝

dataflow:> app register --type sink --name log --uri docker://springcloudstream/log-sink-rabbit:1.3.1.RELEASE --metadata-uri file:///home/.m2/repository/org/springframework/cloud/stream/app/log-sink-rabbit/1.3.1.RELEASE/log-sink-rabbit-1.3.1.RELEASE-metadata.jar
Successfully registered application 'sink:log'
dataflow:>app info --name log --type sink
Information about sink application 'log':
Resource URI: docker://springcloudstream/log-sink-rabbit:1.3.1.RELEASE
╔══════════════════════════════╤══════════════════════════════╤══════════════════════════════╤══════════════════════════════╗
║         Option Name          │         Description          │           Default            │             Type             ║
╠══════════════════════════════╪══════════════════════════════╪══════════════════════════════╪══════════════════════════════╣
║log.name                      │The name of the logger to use.│<none>                        │java.lang.String              ║
║log.level                     │The level at which to log     │<none>                        │org.springframework.integratio║
║                              │messages.                     │                              │n.handler.LoggingHandler$Level║
║log.expression                │A SpEL expression (against the│payload                       │java.lang.String              ║
║                              │incoming message) to evaluate │                              │                              ║
║                              │as the logged message.        │                              │                              ║
╚══════════════════════════════╧══════════════════════════════╧══════════════════════════════╧══════════════════════════════╝

dataflow:> stream create --name ticktock --definition "time | log" --deploy
Created new stream 'ticktock'
Deployment request has been sent
dataflow:> stream list
╔═══════════╤═════════════════╤═════════════════════════════════════════╗
║Stream Name│Stream Definition│                 Status                  ║
╠═══════════╪═════════════════╪═════════════════════════════════════════╣
║ticktock   │time | log       │The stream has been successfully deployed║
╚═══════════╧═════════════════╧═════════════════════════════════════════╝
```
