### ISSUE TITLE
Review reference guide for grammar checks and correctness

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#315]
This is a continuation of SCDF-core docs cleanup via https://github.com/spring-cloud/spring-cloud-dataflow/commit/3729466d1a736043d1f23f95a5144dde7ad05da1#diff-792c746ce6651f378b6f76feae3e9f1b, but for [K8S-server ref. guide](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/tree/master/spring-cloud-dataflow-server-kubernetes-docs).

**Comment by chrisjs** [comment]
merged in 6294d27
