### ISSUE TITLE
Create Helm chart for 1.6.1

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow-server-kubernetes#321]
SCDF 1.6.1.RELEASE
Skipper 1.0.9.RELEASE

**Comment by chrisjs** [comment]
PR @ https://github.com/helm/charts/pull/7188

**Comment by chrisjs** [comment]
also - update docs & patch zip / deploy

**Comment by sabbyanandan** [comment]
The PR is merged and the [chart is available](https://hub.kubeapps.com/charts/incubator/spring-cloud-data-flow) as well. Thanks, @chrisjs!

**Comment by sabbyanandan** [comment]
I was too eager to close it without confirming the chart actually includes v1.6.1 bits; it is not there yet. Let's try it again.

**Comment by chrisjs** [comment]
LGTM - you might need to update your repo:

`helm repo update`

```
$ helm install incubator/spring-cloud-data-flow --version 0.2.5
...
...
$ helm list
NAME          	REVISION	UPDATED                 	STATUS  	CHART                       	NAMESPACE
nuanced-peahen	1       	Thu Aug 16 15:47:29 2018	DEPLOYED	spring-cloud-data-flow-0.2.5	default
$
```
