### ISSUE TITLE
Enable Scheduler feature-toggle by default

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#322]
Depends on:

- [x] https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/pull/5

- [x] https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/pull/6

- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/2404

- [x] https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/247

- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/2405

- [x] https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/issues/4

**Comment by sabbyanandan** [comment]
Look at it from helm-chart perspective also.

**Comment by xyjwsj** [comment]
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerService' defined in class path resource [org/springframework/cloud/dataflow/server/config/features/SchedulerConfiguration.class]: Unsatisfied dependency expressed through method 'schedulerService' parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.scheduler.spi.core.Scheduler' available: expected at least 1 bean which qualifies as autowire candidate.

what's wrong? why? How to do?

**Comment by xyjwsj** [comment]
Not Version: 1.7.0.BUILD-SNAPSHOT？

**Comment by sabbyanandan** [comment]
@xyjwsj: Please follow the issues at [spring-cloud/spring-cloud-scheduler-kubernetes](https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/issues). Given the `CronJob` spec is at BETA, we may not include in our 1.7 GA release. It will, however, will be available in a SNAPSHOT/milestone release. You'd have to wait until we finish the work in progress.

**Comment by xyjwsj** [comment]
ok,Thanks!

**Comment by chrisjs** [comment]
moving this to "in progress" as it has multiple dependencies listed above in the task list

**Comment by chrisjs** [comment]
related issues merged / closed
