### ISSUE TITLE
Config schedules Error

### ISSUE THREAD

**Issue by xyjwsj** [spring-cloud/spring-cloud-dataflow-server-kubernetes#323]
when I config spring.cloud.dataflow.features.schedules-enabled=true, the server display
[Parameter 1 of method schedulerService in org.springframework.cloud.dataflow.server.config.features.SchedulerConfiguration required a bean of type 'org.springframework.cloud.scheduler.spi.core.Scheduler' that could not be found.]

**Comment by cppwfs** [comment]
This feature isn't available in the Spring Cloud DataFlow Server Kubernetes 1.6.0.RELEASE.   We do have an open story for this feature.

**Comment by xyjwsj** [comment]
When can I use it?
