### ISSUE TITLE
image pull policy

### ISSUE THREAD

**Issue by xyjwsj** [spring-cloud/spring-cloud-dataflow-server-kubernetes#326]
I config kubernetes-server SPRING_CLOUD_DEPLOYER_KUBERNETES_DEPLOYMENT_IMAGE_PULL_POLICY=Always,
but when I deploy stream application, the stream application status also is IfNotPresent,
I don't known how to config it

**Comment by sabbyanandan** [comment]
Please refer to the documentation on how to configure [Image Pull Policy](http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.6.1.RELEASE/reference/htmlsingle/#_image_pull_policy) when deploying a stream. You can control this at each app level while deploying the stream/task or you can globally override it at server deployment level.

For questions like this, please use StackOverflow going forward.

**Comment by chrisjs** [comment]
this is a documentation issue. use property `SPRING_CLOUD_DEPLOYER_KUBERNETES_IMAGE_PULL_POLICY`. docs fixed in 1adf583
