### ISSUE TITLE
Bump helm-chart to v1.6.2

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#329]

**Comment by chrisjs** [comment]
this is ready to go when bits are released. only change was bumping DF to 1.6.2, skipper was already at 1.0.9.RELEASE

**Comment by chrisjs** [comment]
PR @ https://github.com/helm/charts/pull/7561

**Comment by chrisjs** [comment]
merged
