### ISSUE TITLE
Connect to MySQL on Amazon Redshift

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow-server-kubernetes#338]
How can i connect mysql to a redshift database by giving the url, user and password?

**Comment by chrisjs** [comment]
You may want to take a look at the JDBC source and sink as a starting point. MySQL would use a JDBC connection and it appears you can interact with Redshift via JDBC as well (https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html)

* JDBC source: https://github.com/spring-cloud-stream-app-starters/jdbc/blob/master/spring-cloud-starter-stream-source-jdbc/README.adoc

* JDBC sink: https://github.com/spring-cloud-stream-app-starters/jdbc/blob/master/spring-cloud-starter-stream-sink-jdbc/README.adoc

That may be a good starting point.

Closing this issue as its not related to DF on Kubernetes.
