### ISSUE TITLE
Cron Expression not being accepted

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#350]
_From @siddhantsorann on October 29, 2018 6:2_

Description:
Cron expressions which have been used in Java are not being accepted. There seems to be an issue with the regex format uploaded to scdf kubernetes server. "0 0 0/1 * * ?" This particular expression represents every hour, every day. But its not being accepted in scdf server as the regex format added there is "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" which doesnt allow spaces, decimals, fraction and "?", all of which are used to represent a cron expression. 
v1.7.0.RELEASE Kubernetes

_Copied from original issue: spring-cloud/spring-cloud-dataflow#2521_

**Comment by chrisjs** [comment]
The expression is dictated by Kubernetes - they use the "standard" fields and expressions except where noted in the docs: https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

Your schedule can be tested outside of data flow and directly against k8s with `kubectl`, for example:

```
$ kubectl run hello --schedule="0 0 0/1 * * ?" --restart=Never --image=busybox -- /bin/sh -c "echo hello"
The CronJob "hello" is invalid: spec.schedule: Invalid value: "0 0 0/1 * * ?": Expected exactly 5 fields, found 6: 0 0 0/1 * * ?
```

**Comment by siddhantsorann** [comment]
@chrisjs I am familiar with that but the issue is that I am unable to add a schedule via the spring cloud dataflow UI. It is not accepting the cron expressions used by kubernetes or any other service.

**Comment by chrisjs** [comment]
@siddhantsorann the schedule you provided is not accepted when using `kubectl` directly - i.e.: without going through data flow as i posted above. do you have a schedule expression that is failing in the data flow UI but works when using `kubectl` directly?

**Comment by siddhantsorann** [comment]
@chrisjs "0 0 0/1 * * ?" is the cron in the expression you provided. This is not being accepted by the scdf server. 
Error:
Failed to create schedule CronJob.batch "test" is invalid: spec.schedule: Invalid value: "0 0 0/1 * * ?": Expected exactly 5 fields, found 6: 0 0 0/1 * * ?

**Comment by chrisjs** [comment]
@siddhantsorann its an invalid expression (below is not SCDF):

```
$ kubectl run hello --schedule="0 0 0/1 * * ?" --restart=Never --image=busybox -- /bin/sh -c "echo hello"
The CronJob "hello" is invalid: spec.schedule: Invalid value: "0 0 0/1 * * ?": Expected exactly 5 fields, found 6: 0 0 0/1 * * ?
$
```

**Comment by cppwfs** [comment]
@siddhantsorann this is not DataFlow that is rejecting the expression.  Its Kubernetes itself.    An example expression would be : `*/1 * * * *` 
If you notice in @chrisjs example above he is using kubectl to create the cronjob.

**Comment by siddhantsorann** [comment]
@cppwfs Thanks. Understood the problem. Different formats.
