### ISSUE TITLE
Spring Cloud Task Execution ID not passed when using SHELL entryPointStyle

### ISSUE THREAD

**Issue by mrbq** [spring-cloud/spring-cloud-dataflow-server-kubernetes#352]
Hi,
When you configure the SCDF server with the "EXEC" entryPointStyle I see the "spring.cloud.task.executionid" parameter being passed as a container arg:
```
    - args:
        - '--spring.cloud.task.executionid=88'
```
But, if you configure the SCDF server with the "SHELL" entryPointStyle that parameter is not passed as an environment variable. 

Best regards,
Marcos.

**Comment by chrisjs** [comment]
Correct - looks like `spring.cloud.task.executionid` is being passed as a command line argument in the `AppDeploymentRequest` - https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskService.java#L223

When using the entry point style of `exec` (the default), command line arguments from the `AppDeploymentRequest` are set onto the container as arguments. 

When using the entry point style of `shell`, command line arguments from the `AppDeploymentRequest` do not get converted into environment variables. existing environment variables get set into the container as environment variables along with application properties.

This isn't specific to `spring.cloud.task.executionid`, it would be the same case as anything else set as a command line argument in the incoming `AppDeploymentRequest`

**Comment by mrbq** [comment]
Hi,

But if that parameter is not passed, in the case that the task runs embedded spring batch job then the job is executed only the first-time the task is run (after that it is considered a duplicated execution of the same job by spring batch).

Thank you.

**Comment by chrisjs** [comment]
is there a reason not to use `exec`? we have out of the box apps that do batch jobs and this works fine. 

a spring batch `JobParametersIncrementer` can be used to avoid duplication, for example: https://docs.spring.io/spring-batch/trunk/reference/html/configureJob.html#JobParametersIncrementer

**Comment by mrbq** [comment]
Hi,

Yes, If I use `exec` then I get a "no executable not found in $PATH error", Could it be an error on how the image is being built? But in the container arguments I do not see a "-jar" option.

Yes, about the `JobParametersIncrementer` it is possible to use it but then I got an error If I want to declare the task as "FAILED" if the batch Job fails, I am using Spring Cloud Task 1.2.3.RELEASE since I can not use the 2.x version because I am using Spring Boot 1.5.x. Besides, I have found some errors if you use the `JobParametersIncrementer` like the one reported here:
https://github.com/spring-cloud/spring-cloud-task/issues/414

Thank you!

**Comment by chrisjs** [comment]
i don't know what your Dockerfile looks like, but for example a Dockerfile that we generate for our out of the box apps looks like:

```
FROM anapsix/alpine-java:8
COPY maven /maven/
VOLUME ["/tmp"]
ENTRYPOINT ["java","-jar","/maven/timestamp-batch-task.jar"]
```

obviously, modify to meet your needs

**Comment by mrbq** [comment]
Hi,
I tested the application with that Dockerfile and it works!!...well there is some other problems but the application seems to be OK.

Thank you!
