### ISSUE TITLE
Scheduler docs point to PCF Scheduler

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#354]
Let's review [this section](http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.7.0.RELEASE/reference/htmlsingle/#_the_scheduler) in the docs in the context of Kubernetes.

**Comment by chrisjs** [comment]
@sabbyanandan  looks like that comes out of https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

given there is only one reference to PCF (that i see):

`For example: on the Cloud Foundry platform Spring Cloud Data Flow will use the PCF Scheduler.`

how about updating that to:

`When using the Cloud Foundry platform Spring Cloud Data Flow will use the PCF Scheduler. When using Kubernetes, a [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) will be used.`

?

**Comment by sabbyanandan** [comment]
Yeah, let's do that instead then. Feel free to move this issue to Core.

**Comment by chrisjs** [comment]
closing in favor of: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2578
