### ISSUE TITLE
Prepare for 1.7.1.RELEASE

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#359]
As part of the 1.7.1.RELEASE, we would have to prepare the following.

- [x] Bump SCDF core to 1.7.2.RELEASE

**Comment by ilayaperumalg** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/360 for Helm repo update.
