### ISSUE TITLE
Submit 1.7.1.RELEASE to Helm Repo

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-server-kubernetes#360]

**Comment by chrisjs** [comment]
PR @ https://github.com/helm/charts/pull/9545

**Comment by chrisjs** [comment]
PR was updated to use 1.7.2 instead, closing this in favor of https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/366
