### ISSUE TITLE
Replicate all the required deployer properties defined in SCDF to Skipper deployment

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#367]
As a developer, I'd like to replicate all the deployer properties defined in SCDF to Skipper, so when the users use SCDF on Skipper mode, they also get a consistent deployment experience as described in the docs.

Currently, SCDF and Skipper are not in sync (property configs are missing in Skipper deployment), so the properties such as liveness and readiness probes don't take into account when the streams are deployed in Skipper mode.

**Comment by chrisjs** [comment]
the same changes need to be replicated to the helm chart, i.e.: https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/364
