### ISSUE TITLE
Expose env-var properties accessible by stream and task applications

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#37]
As a developer, I'd like to investigate how to expose environment variables, so it is accessible by Replication Controller and Boot, bi-directionally. 

_other items to consider:_
The launched application would need to be provided a hint as to the service name in order to resolve the env-var key that could be of pattern: `<servicename>_<namespace>_<host>`

**Acceptance:**
- Design review
- I'm able to successfully discover and bind binders and analytic store by env-var's

**Comment by markpollack** [comment]
It is the other way around.  The replication controller can expose variables which are well known boot properties or can mount a secrets file system with key-Value pairs (in turn exposed as env-vars) that are also well known boot properties.  Can investigate customizing the replication controller to expose specific variables first and prob a separate story , look to use a different strategy for the connector library that does env-var translation from service discovery env-vars that k8s automatically provides.

**Comment by sabbyanandan** [comment]
This relates to spring-cloud/spring-cloud-dataflow-admin-kubernetes#31

**Comment by trisberg** [comment]
No longer relevant AFAICT, we have a way to pass env vars via deployer properties
