### ISSUE TITLE
Deploy a stream with 2 app in a single POD

### ISSUE THREAD

**Issue by anirudha** [spring-cloud/spring-cloud-dataflow-server-kubernetes#373]
Is there a way to currently available or planned for 2 images of a stream to be running within a single pod ?

**Comment by sabbyanandan** [comment]
Hi, @anirudha. Leaving the 2 different docker-images from the criteria aside, there's a way to address the same requirement with the recently added improvements to Spring Cloud Function and Spring Cloud Stream. The function-chaining support [read blog [here](https://spring.io/blog/2018/10/30/spring-cloud-stream-fishtown-rc1-2-1-0-rc1-release-announcement#spring-cloud-function-support)] provides the facility to define the invocation order of the business-logic wrapped as `Function` bean definitions. 

Example from the blog:
> --spring.cloud.stream.function.definition=toUpperCase|wrapInQuotes

Here, we are chaining 2-functions. The events begin at `toUpperCase` and the outcome of this operation is propagated to the next step, which is `wrapInQuotes`. 

With this facility available in the programming model, from SCDF perspective, you can deploy a stream definition with the out-of-the-box or custom apps that can include the function-chain, too.

For instance, you can build a new Spring Boot app (lets say: `new-http-app`) with existing `http-source` configuration [see docs [here](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Darwin.SR3/reference/htmlsingle/#_patching_pre_built_applications)]; in that same application, you can now also define `toUpperCase` and `wrapInQuotes` as `@Bean` definitions. Now at stream deployment time, you can define the function-chain like:

> stream create foo --definition "new-http-app --spring.cloud.stream.function.definition=toUpperCase|wrapInQuotes | filter | cassandra"

This allows the composition of different functions to be part of the same deployment pod, and everything runs in the colocated mode. No message broker involved. No need to have different docker images for each of the functional bits either. 

(We are close to also publishing a blog on this subject very soon - stay tuned)

All that said, if you can think of a scenario where you'd _still_ benefit from independent docker images deployed to a single pod, please open a different issue detailing the use-case requirements at [spring-cloud/spring-cloud-deployer-kubernetes](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues) project. 

Also, for questions like this, please use StackOverflow or Gitter in the future. We use GH for features/bugs.
