### ISSUE TITLE
Override MaxHeapSize setting on Replication Controller

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#38]
As a developer, I'd like to find a way to set `MaxHeapSize` on the Replication Controller, so the jvm that launches the application(s) has customized launch settings. 

This relates to spring-cloud/spring-cloud-stream#356.

**Comment by trisberg** [comment]
Shouldn't this be in `spring-cloud-dataflow/spring-cloud-dataflow-app-launcher`? That's where the launcher lives and I guess we'd have to specify that or provide a placeholder in the startup command for the Docker image.

**Comment by markpollack** [comment]
It should move to here https://github.com/spring-cloud/spring-cloud-kubernetes-deployer
ATM we create the replication controller programmatically , so need a configuration property to set this value.  Eventually we may support templated yml files.

**Comment by trisberg** [comment]
Recent updates should resolve this for the deployer. We can pass in "_JAVA_OPTIONS" with max heap settings.
