### ISSUE TITLE
config multiple values for environmentVariables []

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow-server-kubernetes#380]
Hello, 

how can i deploy using multiple values for  deployer.*.kubernetes.environmentVariables

because, 

 deployer.*.kubernetes.environmentVariables=[JAVA_TOOL_OPTIONS=-Xmx1024m -XX:+UnlockExperimentalVMOptions  -XX:+UseCGroupMemoryLimitForHeap, TZ=Europe/Madrid]
fail

and using double quotes at begin and end fail too

any help?

I need it, because, i need to add "TZ=Europe/Madrid" to fix the date and time from linux machine and containers ( it is running in aws irland and i am at madrid spain,  i need  +1 hour )
Using double quots?

scdf 1.7.3
k8s 1.13
java 8
all default deploys on k8s after same updates ...

**Comment by eskuai** [comment]
sorry, my fault, 

It is working 
deployer.*.kubernetes.readinessProbePath=/info
deployer.*.kubernetes.livenessProbePath=/health
deployer.*.kubernetes.livenessProbeDelay=120
deployer.*.kubernetes.livenessProbePeriod=90
deployer.*.kubernetes.limits.memory=1024Mi
deployer.*.kubernetes.requests.memory=1024Mi
deployer.*.memory=2048
deployer.*.kubernetes.environmentVariables="JAVA_TOOL_OPTIONS=-Xmx1024m -XX:+UnlockExperimentalVMOptions  -XX:+UseCGroupMemoryLimitForHeap,TZ=Europe/Madrid,SPRING_CLOUD_CONFIG_ENABLED=false"


Only using double quote at begin and the end.

Tx

Please closed

Sorry for disturb

**Comment by chrisjs** [comment]
closing, thanks for the update!
