### ISSUE TITLE
It does not look like SPRING_CLOUD_CONFIG_ENABLED to false avoid 

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow-server-kubernetes#381]
It does not look like SPRING_CLOUD_CONFIG_ENABLED to false should be avoid the following message:

**2019-02-18 17:00:36.070  INFO 1 --- [nio-8080-exec-7] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2019-02-18 17:00:36.074  WARN 1 --- [nio-8080-exec-7] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/log-sink/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)**

how can i disable the check for spring cloud config server ???

I am not using skipper , reference to #2199 It does not look like SPRING_CLOUD_CONFIG_ENABLED is working with skipper enabled #2199

Stream definition is simply    time | log

**Comment by sabbyanandan** [comment]
That WARN message shouldn't cause any side effects, but it'd be good not to log it all. 

However, the toggle flag in the [server-deployment.yml](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/d501a96a6244ce7000bdd9b76bf579138c25cc15/src/kubernetes/server/server-deployment.yaml#L37) is _only_ for SCDF, but it looks like you've pasted the logs of the `log-sink` application [i.e., `: I/O error on GET request for "http://localhost:8888/log-sink/default"`]. 

If you want to disable it for the deployed applications, please note that you'd have to set that flag to the deployed applications, as well, separately. 

You can do that via `spring.cloud.deployer.kubernetes.environmentVariables` property either as a global setting or individually at each application level when deploying the stream.

**Comment by sabbyanandan** [comment]
Please consider asking questions like this StacokOverflow going forward.  We use GH for bugs/feature-requests.
