### ISSUE TITLE
 Invalid format for app key 'source.mk-source-sftp-0.0.2.metadata'in file. Must be <type>.<name> or <type>.<name>.metadata

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow-server-kubernetes#386]
Hello,
As a user,  when i 've registered an app jar metada with fail source.mk-source-sftp-0.0.2.metadata.jar
BUT into my nexus repo the correct version is 'source.mk-source-sftp-0.0.1.metadata

This is a error, but, ... SCDF stop working ...

/ ___| _ __  _ __(_)_ __   __ _   / ___| | ___  _   _  __| |
\___ \| '_ \| '__| | '_ \ / _ `| | |   | |/ _ \| | | |/ _` |
 ___) | |_) | |  | | | | | (_| | | |___| | (_) | |_| | (_| |
|____/| .__/|_|  |_|_| |_|\__, |  \____|_|\___/ \__,_|\__,_|
 ____ |_|    _          __|___/                 __________
|  _ \  __ _| |_ __ _  |  ___| | _____      __  \ \ \ \ \ \
| | | |/  _`| __/ _` | | |_  | |/ _ \ \ /\ / /   \ \ \ \ \ \
| |_| | (_| | || (_| | |  _| | | (_) \ V  V /    / / / / / /
|____/ \__,_|\__\__,_| |_|   |_|\___/ \_/\_/    /_/_/_/_/_/

1.3.1.RELEASE

Welcome to the Spring Cloud Data Flow shell. For assistance hit TAB or type "help".
server-unknown:>dataflow config server --username user --password password http://localhost:32055
Shell mode: classic, Server mode: classic
dataflow:>stream list
╔═══════════╤═════════════════╤══════════════════════════════════════════════════════════════════════╗
║Stream Name│Stream Definition│                                Status                                ║
╠═══════════╪═════════════════╪══════════════════════════════════════════════════════════════════════╣
║aaaaa      │time | log       │The app or group is known to the system, but is not currently deployed║
╚═══════════╧═════════════════╧══════════════════════════════════════════════════════════════════════╝

dataflow:>app register
You should specify a default option, otherwise known as 'name' for this command
**dataflow:>app list
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Invalid format for app key 'source.mk-source-sftp-0.0.2.metadata'in file. Must be <type>.<name> or <type>.<name>.metadata**

And , dashboard stop working !

The scdf server always shows :
 Invalid format for app key 'source.mk-source-sftp-0.0.2.metadata'in file. Must be <type>.<name> or <type>.<name>.metadata

And i got to delete from mysql the elements,

MySQL [mysql]> delete  from URI_REGISTRY where NAME='source.mk-source-sftp-0.0.2.metadata';
Query OK, 1 row affected (0.00 sec)

MySQL [mysql]> delete  from URI_REGISTRY where NAME='source.mk-source-sftp-0.0.2';
Query OK, 1 row affected (0.01 sec)

MySQL [mysql]> show tables;

how can i check that an invalid metada reference ?

**Comment by chrisjs** [comment]
looks like an invalid format key per the message. not kubernetes specific, moving to dataflow project given the report indicates registering invalid metadata leads to "dashboard not working" and having to manually delete from DB

**Comment by chrisjs** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow#2979
