### ISSUE TITLE
Adding Kafka support to stable/spring-cloud-data-flow Helm chart

### ISSUE THREAD

**Issue by vxavictor513** [spring-cloud/spring-cloud-dataflow-server-kubernetes#387]
The current official Helm chart, [stable/spring-cloud-data-flow](https://github.com/helm/charts/tree/master/stable/spring-cloud-data-flow) only supports RabbitMQ integration. It'd be great if Kafka integration is added.

**Comment by chrisjs** [comment]
moving to https://github.com/spring-cloud/spring-cloud-dataflow/ as development from 2.x on is done there

**Comment by chrisjs** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow#2996
