### ISSUE TITLE
Cron Expression Validation error fix

### ISSUE THREAD

**Issue by karthikbhat13** [spring-cloud/spring-cloud-dataflow-server-kubernetes#432]
Error message just outputs the regex, which we are almost led to believe that something is wrong with expression, But issue is with schedule name.

Can we fix the error message?

**Comment by sabbyanandan** [comment]
Hi, @karthikbhat13. This repo is not maintained anymore. Please review the note in the [README](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes#note-spring-cloud-data-flow-v20). Perhaps you can open the issue in [SCDF core](https://github.com/spring-cloud/spring-cloud-dataflow) along with more description of the problem, the task definition, and the error message that you're referring to - more details would be helpful.
