### ISSUE TITLE
Stream Partitions

### ISSUE THREAD

**Issue by mhsu0020** [spring-cloud/spring-cloud-dataflow-server-kubernetes#84]
Trying the partition deployment properties mentioned [here](https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/102#issuecomment-220086659)

Data seems to flow to all the log sinks, ignoring the partition expression.

Also if I scale the module pods using kubectl (say increase number of log pods from 2 to 10 ), does the dataflow server recognizes the change and sends data to the correct partition? Or is there some other way to scale the modules?

**Comment by sabbyanandan** [comment]
Hi, @mhsu0020: The stream partitioning feature was recently addressed in the [1.0.0.RELEASE](https://spring.io/blog/2016/07/12/spring-cloud-data-flow-for-kubernetes-1-0-ga-released); please try it out and let us know if you find any anomalies. 

As for the dynamic reshuffling of partitions, it is not supported in 1.0.0.RELEASE. We are working on Kafka 0.9 compliant [binder implementation](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/2) and with that, the dynamic adjustment of the partitions will be supported.
